/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ForexRouteImport } from './routes/forex'
import { Route as ForexIndexRouteImport } from './routes/forex.index'
import { Route as ApiPublicApplyRouteImport } from './routes/api/public/apply'
import { Route as ForexDestinationsSlugRouteImport } from './routes/forex.destinations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexRoute = ForexRouteImport.update({
  id: '/forex',
  path: '/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexIndexRoute = ForexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForexRoute,
} as any)
const ApiPublicApplyRoute = ApiPublicApplyRouteImport.update({
  id: '/api/public/apply',
  path: '/api/public/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexDestinationsSlugRoute = ForexDestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => ForexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/forex': typeof ForexRouteWithChildren
  '/forex/': typeof ForexIndexRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/forex/destinations/$slug': typeof ForexDestinationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/forex': typeof ForexIndexRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/forex/destinations/$slug': typeof ForexDestinationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/forex': typeof ForexRouteWithChildren
  '/forex/': typeof ForexIndexRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/forex/destinations/$slug': typeof ForexDestinationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/forex'
    | '/forex/'
    | '/api/public/apply'
    | '/forex/destinations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/forex'
    | '/api/public/apply'
    | '/forex/destinations/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/forex'
    | '/forex/'
    | '/api/public/apply'
    | '/forex/destinations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  ForexRoute: typeof ForexRouteWithChildren
  ApiPublicApplyRoute: typeof ApiPublicApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex': {
      id: '/forex'
      path: '/forex'
      fullPath: '/forex'
      preLoaderRoute: typeof ForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex/': {
      id: '/forex/'
      path: '/'
      fullPath: '/forex/'
      preLoaderRoute: typeof ForexIndexRouteImport
      parentRoute: typeof ForexRoute
    }
    '/api/public/apply': {
      id: '/api/public/apply'
      path: '/api/public/apply'
      fullPath: '/api/public/apply'
      preLoaderRoute: typeof ApiPublicApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex/destinations/$slug': {
      id: '/forex/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/forex/destinations/$slug'
      preLoaderRoute: typeof ForexDestinationsSlugRouteImport
      parentRoute: typeof ForexRoute
    }
  }
}

interface ForexRouteChildren {
  ForexIndexRoute: typeof ForexIndexRoute
  ForexDestinationsSlugRoute: typeof ForexDestinationsSlugRoute
}

const ForexRouteChildren: ForexRouteChildren = {
  ForexIndexRoute: ForexIndexRoute,
  ForexDestinationsSlugRoute: ForexDestinationsSlugRoute,
}

const ForexRouteWithChildren = ForexRoute._addFileChildren(ForexRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  ForexRoute: ForexRouteWithChildren,
  ApiPublicApplyRoute: ApiPublicApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
